name: "Blog of debuqer"
author:
  name: "MohammadBagher Abbasi"
  username: "debuqer"
  description: "PHP Developer, trying to focus on DEBUGGING"
  profile: "assets/img/profile.jpeg"
server:
  host: "localhost"
  port: "3334"
  url: ""
  ext: "index.html"
template:
  dir: "templates/"
source:
  dir: "source/"
  ext: "md"
routes:
  "/":
    type: "index"
    dir: ""
    template: "index.html"
  "/about":
    type: "index"
    dir: ""
    template: "about.html"
  "/cv":
    type: "index"
    dir: ""
    template: "cv.html"
  "/blog":
    type: "index"
    dir: ""
    template: "blog.html"
  "/blog/post/:filename":
    type: "post"
    dir: "/blog"
    template: "article.html"